image: node

pages:
  stage: deploy
  cache:
    paths:
      - overview/node_modules/
  script:
    - cd overview
    - npm install
    - CI=false npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - cd ..
    - mv overview/build public
  artifacts:
    paths:
      - public
