stages:
  - deploy-vm
  - test




update-code-on-vm:
  image: alpine:latest
  stage: deploy-vm
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd wi-inf-projekt-2-greenbpm/; git fetch; git pull;"
  environment:
    name: production
    url: http://vm11.fkc.hft-stuttgart.de
  only:
    - develop


postman_tests:
  stage: test
  image: 
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
   - chmod og= $ID_RSA
   - apk update && apk add openssh-client
   - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd wi-inf-projekt-2-greenbpm/;"
   - newman --version
   - cd  repository
   - newman run collection.json