image: node
stages:
  - build
  - deploy
maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar
pages:
  stage: deploy
  variables:
    PUBLIC_URL: "/wi-inf-projekt-2-greenbpm"
  cache:
    paths:
      - overview/node_modules/
  script:
    - cd overview
    - npm install
    - CI=false npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - cd ..
    - mv overview/build public
  artifacts:
    paths:
      - public

