stages:
  - deploy-vm


deploy-overview-vm:
  variables:
    TAG_LATEST: overview:latest
    TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  image: alpine:latest
  stage: deploy-vm
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker build -t $TAG_LATEST wi-inf-projekt-2-greenbpm/overview/"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f overview || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 3001:3000 --name overview $TAG_LATEST"
  environment:
    name: production
    url: http://vm11.fkc.hft-stuttgart.de
  only:
    - develop

deploy-repo-vm:
  variables:
    TAG_LATEST: repo:latest
    TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  image: alpine:latest
  stage: deploy-vm
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker build -t $TAG_LATEST wi-inf-projekt-2-greenbpm/repository/"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f repo || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 8084:8084 --name repo $TAG_LATEST"
  environment:
    name: production
    url: http://vm11.fkc.hft-stuttgart.de
  only:
    - develop
