stages:
  - deploy-vm

update-code-on-vm:
  image: alpine:latest
  stage: deploy-vm
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd wi-inf-projekt-2-greenbpm/; git fetch; git pull;"
  environment:
    name: production
    url: http://vm11.fkc.hft-stuttgart.de
  only:
    - develop

deploy-overview-vm:
  variables:
    TAG_LATEST: overview:latest
    TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  image: alpine:latest
  stage: deploy-vm
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "fuser -KILL -k -n tcp 3000"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd wi-inf-projekt-2-greenbpm/overview/; ls; npm install;"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sh -c 'cd /wi-inf-projekt-2-greenbpm/overview/; nohup npx serve build > /dev/null 2>&1 &'"
  environment:
    name: production
    url: http://vm11.fkc.hft-stuttgart.de
  only:
    - develop

deploy-repo-vm:
  variables:
    TAG_LATEST: repo:latest
    TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  image: alpine:latest
  stage: deploy-vm
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "fuser -KILL -k -n tcp 8084"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd wi-inf-projekt-2-greenbpm/repository/; mvn clean install;"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd wi-inf-projekt-2-greenbpm/repository/target/ && java -jar springboot-backend-0.0.1-SNAPSHOT.jar &"
  environment:
    name: production
    url: http://vm11.fkc.hft-stuttgart.de
  only:
    - develop
