
# Functions that should be executed before the build script is run
before_script: []
stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - cd overview
    - npm ci
    - CI=false npm run build
  artifacts:
    paths:
      - overview/build/

pages:
  image: alpine:latest
  stage: deploy
  script:
    # Rename the CRA `build` folder to `public`
    - mkdir public
    - cp overview/build public -r
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
